name: aia_mobile_test_flutter
description: "A AIA Project Test"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  formz: ^0.8.0
  equatable: ^2.0.7
  easy_localization: ^3.0.7+1
  shared_preferences: ^2.5.2
  pretty_dio_logger: ^1.4.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_image_carousel_slider: ^2.0.1
  flutter_chat_ui: ^1.6.15
  uuid: ^4.5.1
  speech_to_text: ^7.0.0
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.16
  flutter_tts: ^4.2.2
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/vectors/
    - assets/translations/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900
